// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AwsCredentialType } from "./AwsCredentialType";

export type BedrockSetupParams = { "type": "profile", profile: string, region: string, } | { "type": "environment", credentialType: AwsCredentialType, region: string, } | { "type": "accessKeys", accessKeyId: string, secretAccessKey: string, sessionToken?: string | null, region: string, };
